# Generated by Django 5.2.8 on 2025-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_qr_code_booking_ticket_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
